### ISSUE TITLE
有没有开源的打算？

### ISSUE THREAD

**Issue by kaybinwong** [neil-pan-s/twist-quant#4]
有没有开源的打算？

**Comment by neil-pan-s** [comment]
壹缠非开源项目  如果想要自行扩展二次开发 可以了解下壹缠量化脚本:

脚本编辑器 - https://one-quant.com/#/twist?editor
脚本开发文档 - https://github.com/neil-pan-s/twist-quant/blob/main/PROGRAM.md

**Comment by kaybinwong** [comment]
好的，谢谢楼主
