### ISSUE TITLE
这笔是不是不应该画？

### ISSUE THREAD

**Issue by jimmykuu** [neil-pan-s/twist-quant#6]
SH000001 大盘指数，2020-11-10～2020-11-13，顶底分型之间无独立 K 线，却画了一笔

![2021-11-22-11.37.39.png](https://b.picbed.cn/file/picbed-cn/2021/11/22/2021-11-22-11.37.39.png)

**Comment by neil-pan-s** [comment]
跳空缺口视为一K 壹缠支持配置 你修改为不视为1K就不会成笔 根据个人习惯配置下就行

**Comment by jimmykuu** [comment]
理解了，感谢解释
